In [1]:
import numpy as np
import pandas as pd
import os 

A) Commençons par démontrer que la matrice $\bm{H}$ est orthogonale. Par définition, une matrice est orthogonale si $\bm{H}^T\bm{H}=\bm{I}$, où $\bm{I}$ est la matrice identité.

$$\bm{H}^T\bm{H}=\bm{I}$$
$$\bigg[\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}\bigg]^T \bigg[\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}\bigg]=\bm{I}$$

En utilisant les propriétés suivantes:\
1)$(\bm{A}-\bm{B})^T=\bm{A}^T-\bm{B}^T$\
2) $(\bm{v}\bm{v}^T)^T=(\bm{v}^T)^T\bm{v}^T=\bm{v}\bm{v}^T$\
3) $(\bm{v}^T\bm{v})^T=\bm{v}^T(\bm{v}^T)^T=\bm{v}^T\bm{v}$\
\
Il en découle que : 
$$\bigg[\bm{I}^T-\frac{2(\bm{v}\bm{v}^T)^T}{(\bm{v}^T\bm{v})^T}\bigg] \bigg[\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}\bigg]=\bigg[\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}\bigg] \bigg[\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}\bigg]=\bm{I}$$
$$\bm{I}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}-\frac{2\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}+\frac{4\bm{v}\bm{v}^T \bm{v}\bm{v}^T}{(\bm{v}^T\bm{v})^2}=\bm{I}-\frac{4\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}+\frac{4\bm{v}(\bm{v}^T \bm{v})\bm{v}^T}{(\bm{v}^T\bm{v})^2}=\bm{I}$$
$$\bm{I}-\frac{4\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}+\frac{4\bm{v}\bm{v}^T}{\bm{v}^T\bm{v}}=\bm{I}$$
$$\bm{I}=\bm{I}$$
La matrice $\bm{H}$ est donc orthogonale. En ce qui concerne la matrice Q, elle est définie comme :
$$Q=\begin{bmatrix}
    \bm{I}& 0 \\
    0& \bm{H}
\end{bmatrix}$$
$$\bm{Q}^T\bm{Q}=\begin{bmatrix}
    \bm{I}^T&0\\
    0& \bm{H}^T
\end{bmatrix} \cdot \begin{bmatrix}
    \bm{I}&0\\
    0& \bm{H}
\end{bmatrix}$$
$$\bm{Q}^T\bm{Q}= \begin{bmatrix}
    \bm{I}\cdot \bm{I} & 0 \\
    0 & \bm{H}^T\cdot \bm{H}\\
\end{bmatrix}$$
Mais puisque $\bm{H}$ est orthogonale, il s'ensuit que $\bm{H}^T\bm{H}=\bm{I}$ donc:
$$\bm{Q}^T\bm{Q}= \begin{bmatrix}
    \bm{I} & 0 \\
    0 & \bm{I}\\
\end{bmatrix}=\bm{I}$$
La matrice $\bm{Q}$ est donc elle aussi orthogonale.

B) L'équation 2.1.5 dicte que $\bm{Q}=\bm{Q_0}^T\bm{Q_1}^T\bm{Q_2}^T...\bm{Q_{n-1}}^T$. En utilisant la propriétés $\bm{(ab)^T=(\bm{b}^T\bm{a}^T)}$:
$$\bm{Q}^T\bm{Q}=(\bm{Q_0}^T\bm{Q_1}^T...\bm{Q_{n-1}}^T)^T\cdot\bm{Q_0}^T\bm{Q_1}^T...\bm{Q_{n-1}}^T$$
$$\bm{Q}^T\bm{Q}=\bm{Q_{n-1}}...\bm{Q_1}\bm{Q_0}\bm{Q_0}^T\bm{Q_1}^T...\bm{Q_{n-1}}^T$$
Puisque les matrices de réflexions $\bm{Q_i}$ sont orthogonales, $\bm{Q_i}^T\bm{Q_i}=\bm{Q_i}\bm{Q_i}^T=\bm{I}$
$$\bm{Q}^T\bm{Q}=\bm{Q_{n-1}}...\bm{Q_1}\bm{I}\bm{Q_1}^T...\bm{Q_{n-1}}^T=\bm{Q_{n-1}}...\bm{I}...\bm{Q_{n-1}}^T=\bm{I}$$
La matrice $\bm{Q}$ est donc orthogonale

In [2]:
# C) Implémentation de la fonction Householder_qr
    # argument --> matrice A possédant m rangées et n colonnes
    # retourne --> les matrices Q et R obtenues par la méthode de Householder_qr
def householder_qr(A): #Matrice A 
    m, n= A.shape
    R = A
    Q_matrice = []
    for i in range(n):

        x = R[-(R.shape[0] - i) : , i]
        x = np.expand_dims(x, axis=1)
        
        norm_x= np.linalg.norm(x)
 
        signe = 1 if x[0] >= 0 else -1

        e_1 = np.array([1 if j == 0 else 0 for j in range((m - i))])
        e_1 = np.expand_dims(e_1, axis=1) #Transpose le vecteur
        v = (signe* norm_x * e_1) + x 

        denominator = np.dot(np.transpose(v), v)
        if denominator == 0:
            H = np.eye(len(x))
        else:
            H = np.eye(m - i) - 2 * (np.dot(v, np.transpose(v)) / np.dot(np.transpose(v), v))
        
        
        Q_i = np.eye(m)
        Q_i[i:, i:] = H
        
        R = np.dot(Q_i, R)
        Q_matrice.append(Q_i)
    Q=np.transpose(Q_matrice[0])
    for i in Q_matrice[1:]:
        Q = np.matmul(Q, np.transpose(i))
    return(Q, R)

  
#D)
A= np.array([[1, 2, 3],[3,4,6],[1,3,4],[6,8,2]])
B = np.array([[11, 25, 33],[63,744,61],[14,213,34],[67,98,24]])
C = np.array([[6, 45, 1],[87,36,27],[162,23,90],[11, 12,50]])
D = np.array([[74, 41,22],[217,97,94],[131,159,183],[181, 141,605]])

print(np.linalg.qr(A))
print(householder_qr(A))

#e)

QRResult(Q=array([[-0.14586499,  0.35008431, -0.18747352],
       [-0.43759497, -0.08450311, -0.86837735],
       [-0.14586499,  0.91746232,  0.07498941],
       [-0.87518995, -0.16900622,  0.45293603]]), R=array([[-6.8556546 , -9.48122445, -5.39700469],
       [ 0.        ,  1.7624934 ,  3.8750711 ],
       [ 0.        ,  0.        , -4.56685498]]))
(array([[-0.14586499,  0.35008431, -0.18747352, -0.90610047],
       [-0.43759497, -0.08450311, -0.86837735,  0.21746411],
       [-0.14586499,  0.91746232,  0.07498941,  0.36244019],
       [-0.87518995, -0.16900622,  0.45293603, -0.01812201]]), array([[-6.85565460e+00, -9.48122445e+00, -5.39700469e+00],
       [ 9.68928339e-17,  1.76249340e+00,  3.87507110e+00],
       [ 3.90675701e-17,  6.58795015e-18, -4.56685498e+00],
       [-3.01288242e-16,  4.04275783e-17, -1.59638688e-16]]))


PARTIE 2: Mesures imprécises dans un jeu de bataille navale

In [88]:
#a) Implémentation de l'argument "réduite=True"
def householder_qr(A, réduite): #Matrice A 
    #def de Q_i
    m, n= A.shape
    R = A
    Q_matrice = []
    for i in range(n):

        x = R[-(R.shape[0] - i) : , i]
        x = np.expand_dims(x, axis=1)
        
        norm_x= np.linalg.norm(x)
 
        signe = 1 if x[0] >= 0 else -1

        e_1 = np.array([1 if j == 0 else 0 for j in range((m - i))])
        e_1 = np.expand_dims(e_1, axis=1) #Transpose le vecteur
        v = (signe* norm_x * e_1) + x 

        denominator = np.dot(np.transpose(v), v)
        if denominator == 0:
            H = np.eye(len(x))
        else:
            H = np.eye(m - i) - 2 * (np.dot(v, np.transpose(v)) / np.dot(np.transpose(v), v))
        
        
        Q_i = np.eye(m)
        Q_i[i:, i:] = H
        
        R = np.dot(Q_i, R)
        Q_matrice.append(Q_i)
    Q=np.transpose(Q_matrice[0])
    for i in Q_matrice[1:]:
        Q = np.matmul(Q, np.transpose(i))

    if réduite:
        m, n = R.shape
        R=R[:n]
        Q = Q[:, :-(m-n)]
        return(Q,R)
    else:
        return(Q, R)
    
#A = np.array([[1,2], [3, 2], [4, 1], [6,2]])
#householder_qr(A, réduite=True)



#b)
#{} \ []

path= os.path.abspath("bataille_navale_equipe06.csv")
xdata = pd.read_csv(path, header=0).iloc[:, 0]


x=np.zeros((8,3))

for i in range(len(xdata)):
    x[i, 0] = 1
    x[i, 1] = xdata[i]
    x[i, 2] = xdata[i]**2

Q, R = householder_qr(x, réduite=True)
print(Q)
print(R)

QT=np.transpose(Q)
#RESTE A FAIRE: POSER R*ALPHA=QT*Y,
#R_22*ALPHA_2=QT*Y_2


y = pd.read_csv(path, header=0).iloc[:, 1]
y=y.to_numpy()
y = np.expand_dims(y, axis=1)







[[-0.35355339 -0.54003265  0.53996482  0.00757065  0.03588642 -0.03810835
  -0.21454601 -0.4929253 ]
 [-0.35355339 -0.3858456   0.07730777  0.07623454  0.23814145  0.37019538
   0.47261072  0.54517714]
 [-0.35355339 -0.23145904 -0.23154517 -0.52280671 -0.51201912 -0.37391351
  -0.1082494   0.28424261]
 [-0.35355339 -0.07713696 -0.38586329  0.79268448 -0.21088821 -0.18123429
  -0.11830152 -0.02226574]
 [-0.35355339  0.07722113 -0.38578981 -0.21955819  0.75766441 -0.23061538
  -0.18437473 -0.10375194]
 [-0.35355339  0.23145751 -0.23145339 -0.17200376 -0.21308777  0.76419905
  -0.2401788  -0.22622779]
 [-0.35355339  0.38582615  0.07741594 -0.06456779 -0.12309039 -0.19679502
   0.7141954  -0.38989917]
 [-0.35355339  0.53996946  0.53996313  0.10244677  0.0273932  -0.11372789
  -0.32115567  0.40565018]]
[[-2.82842712e+00 -6.75288637e+03 -1.61968066e+07]
 [ 1.69580237e-16 -4.58271585e+02 -2.18826537e+06]
 [-1.69558937e-16  9.87838843e-15  6.47976174e+04]
 [-2.37732527e-18  8.46666662e-15 -3.5